[package]
name = "sysutil"
version = "0.4.7"
authors = ["ryzeon-dev"]
edition = "2021"
description = "Linux system utils library"
license = "AGPL-3.0-or-later"
repository = "https://github.com/ryzeon-dev/sysutil"
readme = "README.md"

[lib]
path = "src/lib.rs"

[dependencies]
rsjson = "0.4.2"